// Mocks generated by Mockito 5.4.4 from annotations
// in mobile_app/test/features/profile/presentation/pages/create_profile_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mobile_app/features/profile/data/profile_repository.dart'
    as _i3;
import 'package:mobile_app/features/profile/domain/user_profile.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserProfile_0 extends _i1.SmartFake implements _i2.UserProfile {
  _FakeUserProfile_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i3.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserProfile?> getProfile() => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
        ),
        returnValue: _i4.Future<_i2.UserProfile?>.value(),
      ) as _i4.Future<_i2.UserProfile?>);

  @override
  _i4.Future<_i2.UserProfile> createProfile({
    required String? displayName,
    required _i2.PrimaryGoal? primaryGoal,
    _i2.AgeRange? ageRange,
    _i2.Gender? gender,
    double? heightCm,
    double? weightKg,
    _i2.WorkStyle? workStyle,
    _i2.ExerciseAvailability? exerciseAvailability,
    _i2.ScheduleStability? scheduleStability,
    List<_i2.Derailer>? derailers,
    String? preferredWorkoutStyle,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProfile,
          [],
          {
            #displayName: displayName,
            #primaryGoal: primaryGoal,
            #ageRange: ageRange,
            #gender: gender,
            #heightCm: heightCm,
            #weightKg: weightKg,
            #workStyle: workStyle,
            #exerciseAvailability: exerciseAvailability,
            #scheduleStability: scheduleStability,
            #derailers: derailers,
            #preferredWorkoutStyle: preferredWorkoutStyle,
            #notes: notes,
          },
        ),
        returnValue: _i4.Future<_i2.UserProfile>.value(_FakeUserProfile_0(
          this,
          Invocation.method(
            #createProfile,
            [],
            {
              #displayName: displayName,
              #primaryGoal: primaryGoal,
              #ageRange: ageRange,
              #gender: gender,
              #heightCm: heightCm,
              #weightKg: weightKg,
              #workStyle: workStyle,
              #exerciseAvailability: exerciseAvailability,
              #scheduleStability: scheduleStability,
              #derailers: derailers,
              #preferredWorkoutStyle: preferredWorkoutStyle,
              #notes: notes,
            },
          ),
        )),
      ) as _i4.Future<_i2.UserProfile>);

  @override
  _i4.Future<_i2.UserProfile> updateProfile(_i2.UserProfile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [profile],
        ),
        returnValue: _i4.Future<_i2.UserProfile>.value(_FakeUserProfile_0(
          this,
          Invocation.method(
            #updateProfile,
            [profile],
          ),
        )),
      ) as _i4.Future<_i2.UserProfile>);

  @override
  _i4.Future<bool> hasProfile() => (super.noSuchMethod(
        Invocation.method(
          #hasProfile,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
